version: '3'
services:
  postgres-checkly:
    image: "postgres:14.2-alpine"
    container_name: postgres-checkly
    restart: always
    environment:
      - POSTGRES_DB=checkly
      - POSTGRES_USER=checkly
      - POSTGRES_PASSWORD=checkly
    volumes:
      - "~/pgdata:/var/lib/postgresql/data"
      - "./backend/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U checkly" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend-checkly:
    image: "backend-checkly"
    container_name: backend-checkly
    volumes:
      - "./backend/src/etc:/app/etc:ro"
      - "./backend/logs:/app/logs"
    depends_on:
      postgres-checkly:
        condition: service_healthy
  nginx-checkly:
    image: "nginx-checkly"
    container_name: "nginx-checkly"
    ports:
      - "80:8080"
    volumes:
      - "./frontend/nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./frontend/logs:/app/logs"
    depends_on:
      - backend-checkly
